In [4]:
import pandas as pd
import csv

records = []    #create an empty array to store the purchase records of customers
idMap = {}      #initialize an empty set to store food names and ids

with open("data/categories.csv") as foodIDs:
    food = csv.reader(foodIDs)          #open the ID file to be read

    for line in food:
        id = int(line[0].strip())       #take the ID from the first entry of the file
        idMap[id] = line[1].strip()     #record the foods name in the idMap, related to its food ID


with open("data/data.csv", "r") as file:
    data = csv.reader(file)         #open the data to be read

    for line in data:
        time = line[0]          #records the time spent for each customer
        customer = line[1].strip()      #records customer ID, removes whitespace
        basket = []         #initialize an empty an array to store the food bought

        for cell in line[2:]:   #reads the rest of the cells in the row
            item = int(cell.strip())    #converts the cell entry to an integer
            if item in idMap:           #checks if the item is in the ID list
                basket.append(idMap[item])      #adds the name of the item to the customer's purchases

        records.append({            #puts the formatted data into the records array
            "Time": time,
            "customer_ID": customer,
            "items": basket
        })

dataframe = pd.DataFrame(records)

display(dataframe)

     Time customer_ID                                              items
0     490           0  [Frozen Food, Beer+Wine, Milk+Cream+Yogurt, Ju...
1     495           1  [Juices, Ice Cream, Beer+Wine, Deli Foods, Cer...
2     498           2  [Baking Products, Spices+Herbs, Pasta+Noodles,...
3     502           3  [Frozen Food, Frozen Food, Frozen Food, Vegeta...
4     503           4  [Baking Products, Rice, Ice Cream, Vegetables:...
..    ...         ...                                                ...
995  4326         995  [Breads, Milk+Cream+Yogurt, Beans, Canned Food...
996  4333         996  [Baking Products, Other, Breads, International...
997  4342         997  [Frozen Food, Jellies+Jams+Preserves, Pasta+No...
998  4349         998  [Potatoes, Junk Food, Pasta+Noodles, Vegetable...
999  4354         999  [Diapers, Canned Food, Pet Items, Sauces, Cand...

[1000 rows x 3 columns]

In [11]:
from mlxtend.frequent_patterns import apriori, association_rules
from mlxtend.preprocessing import TransactionEncoder

transactions = dataframe["items"].tolist()      #the next few lines change the data into a list so
te = TransactionEncoder()                       #that it can be used in the apriori function, following
te_array = te.fit(transactions).transform(transactions)     #the documentation at geeksforgeeks.com
df_encoded = pd.DataFrame(te_array, columns = te.columns_)

display(df_encoded)

,Baking Products,Beans,Beer+Wine,Breads,Butter,Candy,Canned Food,Cereals,Chocolate,Condiments,...,Other,Pasta+Noodles,Pet Items,Potatoes,Rice,Sauces,Spices+Herbs,Vegetables: Greens,Vegetables: Other,Vegetables: Root
0,True,True,True,False,True,True,True,True,True,False,...,False,True,True,True,True,True,False,True,True,True
1,True,True,True,True,True,True,False,True,True,True,...,True,False,True,True,True,True,True,True,True,True
2,True,False,True,True,True,True,False,True,False,True,...,True,True,False,True,True,True,True,True,True,True
3,False,True,False,False,True,False,False,False,True,True,...,False,True,False,False,False,False,True,True,True,False
4,True,True,False,False,False,True,True,True,True,True,...,False,True,True,True,True,True,True,False,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,False,True,True,True,True,True,True,True,False,True,...,False,True,False,True,True,True,True,True,False,False
996,True,False,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,False,True
997,True,False,True,True,True,False,False,True,True,False,...,True,True,True,False,True,False,False,True,True,False
998,True,False,False,True,True,True,False,False,False,True,...,True,True,False,True,False,True,False,True,False,True
999,False,True,True,True,True,True,True,True,True,True,...,False,True,True,True,True,True,True,True,True,True

In [14]:
frequent_itemsets = apriori(df_encoded, min_support = .3, use_colnames=True)
print("Total Frequent Itemsets", frequent_itemsets.shape[0])
display(frequent_itemsets   )

Total Frequent Itemsets 654

     support                                           itemsets
0      0.585                                  (Baking Products)
1      0.600                                            (Beans)
2      0.602                                        (Beer+Wine)
3      0.578                                           (Breads)
4      0.585                                           (Butter)
..       ...                                                ...
649    0.304             (Potatoes, International Food, Sauces)
650    0.310   (Potatoes, International Food, Vegetables: Root)
651    0.305      (Vegetables: Other, Rice, International Food)
652    0.301  (Vegetables: Root, International Food, Spices+...
653    0.305  (Vegetables: Other, International Food, Vegeta...

[654 rows x 2 columns]